/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JInternalFrameConsultas extends javax.swing.JInternalFrame {
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    /**
     * Creates new form JInternalFrameConsultas
     */
    public JInternalFrameConsultas() {
        initComponents();
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Existencia");
        this.jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldConsulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Nombre a consultar:");

        jTextFieldConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldConsultaKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldConsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldConsultaKeyReleased
        // TODO add your handling code here:
        int i = 0;
        String datos[] = new String[3];
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (Principal.lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Lista vacía");
            }else{
                String datoBuscar = this.jTextFieldConsulta.getText().trim();
                for (i = 0; i < Principal.lista.size(); i++) {
                    if (datoBuscar.equals(Principal.lista.get(i).getNomP())) {
                        if (modelo.getRowCount() != 0) { //si hay datos en pantalla de la consulta anterior
                            modelo.removeRow(0); //borra renglon
                            this.jTable1.repaint(); //repinta la tabla
                        }
                        datos[0] = Principal.lista.get(i).getNomP();
                        datos[1] = Double.toString(Principal.lista.get(i).getPrecio()); //se recupera double se cambia a string
                        datos[2] = Integer.toString(Principal.lista.get(i).getExistencia()); //se recupera entero se cambia a string
                        modelo.addRow(datos); //se agregan los datos a la tabla
                        break;
                    }
                }
                if (i == Principal.lista.size()) {
                    JOptionPane.showMessageDialog(this, "El nombre no está en la lista");
                }
            }
        }
        
    }//GEN-LAST:event_jTextFieldConsultaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldConsulta;
    // End of variables declaration//GEN-END:variables
}
